charge_invite:
  url: /charge/invite.json
  param: { module: charge, action: invite, sf_format: json }
  requirements: { sf_method: [post] }
charge_mail:
  url: /charge/mail.json
  param: { module: charge, action: mail, sf_format: json }
  requirements: { sf_method: [post] }
charge_creditcard:
  url: /charge/creditcard.json
  param: { module: charge, action: creditcard, sf_format: json }
  requirements: { sf_method: [post] }
